In [54]:
import pandas
import scipy
import numpy
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import StandardScaler

In [40]:
url = 'diabetes.csv'
dataframe = pandas.read_csv(url,index_col=1)
array = dataframe.values
print(dataframe.head(10))
dataframe.info()

         Pregnancies  BloodPressure  SkinThickness  Insulin   BMI  \
Glucose                                                             
148                6             72             35        0  33.6   
85                 1             66             29        0  26.6   
183                8             64              0        0  23.3   
89                 1             66             23       94  28.1   
137                0             40             35      168  43.1   
116                5             74              0        0  25.6   
78                 3             50             32       88  31.0   
115               10              0              0        0  35.3   
197                2             70             45      543  30.5   
125                8             96              0        0   0.0   

         DiabetesPedigreeFunction  Age  Outcome  
Glucose                                          
148                         0.627   50        1  
85                   

In [58]:
print('Rescaling')
#seperate array to input and output components
X = array[:,0:7]
Y = array[:,7]
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(X)

#summarize transformed data 
numpy.set_printoptions(precision=3)
print(rescaledX[0:5,:])

Rescaling
[[0.353 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.328 0.354 0.199 0.642 0.944 0.2  ]]


In [53]:
print('Binarize Data')
# separate array into input and output components
X = array[:,0:7]
Y = array[:,7]
binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)
 
# summarize transformed data
numpy.set_printoptions(precision=3)
print(binaryX[0:5,:])

Binarize Data
[[1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1.]]


In [56]:
print('Standardize Data')
# separate array into input and output components
X = array[:,0:7]
Y = array[:,7]
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
 
# summarize transformed data
numpy.set_printoptions(precision=3)
print(rescaledX[0:5,:])

Standardize Data
[[ 0.64   0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]
